import { Inter } from "next/font/google";
import "./globals.css";
import 'material-symbols';
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });
import { VeeContextProvider } from "@/components/context/Chatcontext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body >
      <VeeContextProvider>
        {children}
        <Toaster className="custom-toaster" richColors position="top-right" />
        </VeeContextProvider>
        </body>
    </html>
  );
}
